### ISSUE TITLE
Define 0.4 Kernel and Kernel Library Scope

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fablab#107]
In `v0.4`, we're referring to the extensible `model` framework, along with the corresponding support structures and APIs (selectors, cascading variables, skeleton, etc.) as "the kernel".

In `v0.4` we're referring to all of the library functions for `ssh` puppetry, file synchronization, key generation and management, and all of the other stock routines as "the kernel library" (a la "the c library").

Put together a strawman scope for what the contents of the kernel and the kernel library consist of for `v0.4` as a living document in the `docs` tree.

**Comment by plorenz** [comment]
v0.4 is complete, starting on v0.5, closing out v0.4 framing issues
