### ISSUE TITLE
Factory, Action, Stage "Indexing"

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fablab#27]
In #14. we introduced the concept of "factories", alongside the existing actions and lifecycle stages. With the introduction of parenting (#18), we're now allowing those component collections to be amended in "sub-models". The current implementation works great for additive changes, or wholesale replacements of these sets. Where it breaks down is when we want to examine, or selectively remove from those component collections.

Implement better metadata and support for iterating and adjusting these collections programmatically.

**Comment by plorenz** [comment]
I think by adding the Entity model as well as selectors, this is probably covered. I haven't hit any gaps in model manipulation recently.
