### ISSUE TITLE
Smarter Restart Semaphore in Infrastructure Stage

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fablab#28]
As a part of expressing infrastructure, our current models update operating system packages and restart the model instances. The models include a `semaphore_0.Restart` semaphore, to wait and check for model instance restart.

This is painful in those situations where you're running `fablab up`, or otherwise want to work through the `infrastructure` lifecycle stage, and you know there is no need to wait for the hosts to restart.

We should attempt to make this workflow smarter, to eliminate unnecessary waits. May require `fablab` to handle state tracking (#2) in a better way, first.

**Comment by plorenz** [comment]
We've worked around this by working off of images which are already up to date, so no restart is needed. It's possible that still would be a nice to have in some circumstances, but closing until we hit those circumstances.
