### ISSUE TITLE
Characterization Scalability Targets

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fablab#36]
Incorporate scalability target testing and validation as part of the `zitilib/characterization/ziti` model:

## Endpoints

* Maximum Concurrent Sessions
* Maximum Concurrent Connections
* Maximum Concurrent Services

## Fabric

* Maximum Concurrent Routers
* Maximum Concurrent Sessions
* Maximum Concurrent Services

**Comment by plorenz** [comment]
Ziti specific work shouldn't be tracked in fablab
