### ISSUE TITLE
Generalized SDK Approach

### ISSUE THREAD

**Issue by michaelquigley** [openziti/fablab#7]
`fablab` is intended to primarily act as a software framework, which can be extended and customized by developers (using code) to meet their needs. This means we're going to need an SDK-style workflow, which can acccomodate things like `fablab new`, and the static template files that are included, in addition to the framework code (and models) itself.

Refine the generalized SDK strategy.

**Comment by michaelquigley** [comment]
See package `embed` in `golang` 1.16:

https://tip.golang.org/pkg/embed/

**Comment by plorenz** [comment]
Complete. Fablab is now usable as a library. Resources from fablab can be embedded in applications.
